# Generated by Django 5.2.17 on 2026-09-29 16:07

from django.db import migrations, models

from portal import auditchain


def chain_existing(apps, schema_editor):
    """Seal the rows written before the chain existed, oldest first, one chain per event."""
    AuditLog = apps.get_model("portal", "AuditLog")
    for entry in AuditLog.objects.order_by("id").iterator():
        auditchain.seal(AuditLog, entry)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_t3_voting_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(chain_existing, migrations.RunPython.noop),
    ]
